meta_product_name: "ZeroHunger"
meta_title: "ZeroHunger - No more waste"
meta_description: "App for retailers customers and charities to fight food waste"
meta_image: "charity2.png"
# twitter_account: "@product_twitter_account"
